version: '3.8'

volumes:
  
  mariadb:
    driver: local

services:

  mariadb:
    image: mariadb:10.8.2
    container_name: mariadb
    volumes: 
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret